name: HACS validation
on:
  pull_request:
  push:
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: HACS validation
        uses: "hacs/action@main"
        with:
          category: "theme"
